// Re-exporta todas as funções admin do arquivo functions (que usa o guard de token correto)
export {
  getPromotions,
  createPromotion,
  updatePromotion,
  deletePromotion,
  getNews,
  createNews,
  updateNews,
  deleteNews,
  getProgramacaoAdmin,
  createProgramacao,
  updateProgramacao,
  deleteProgramacao,
  getPodcastsAdmin,
  createPodcast,
  updatePodcast,
  deletePodcast,
  createAdminUser,
  getPromotionEntries,
  deletePromotionEntry,
  getUploadUrl,
  triggerAutoNewsManual,
  getSiteSettings,
  updateSiteSettings,
} from "./admin-api.functions";
