/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PromocoesRouteImport } from './routes/promocoes'
import { Route as ProgramacaoRouteImport } from './routes/programacao'
import { Route as NoticiasRouteImport } from './routes/noticias'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as ApiPublicDebugEnvRouteImport } from './routes/api/public/debug-env'
import { Route as ApiCronNewsRouteImport } from './routes/api/cron.news'
import { Route as ApiPublicCronNewsRouteImport } from './routes/api/public/cron.news'

const PromocoesRoute = PromocoesRouteImport.update({
  id: '/promocoes',
  path: '/promocoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramacaoRoute = ProgramacaoRouteImport.update({
  id: '/programacao',
  path: '/programacao',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasRoute = NoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDebugEnvRoute = ApiPublicDebugEnvRouteImport.update({
  id: '/api/public/debug-env',
  path: '/api/public/debug-env',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronNewsRoute = ApiCronNewsRouteImport.update({
  id: '/api/cron/news',
  path: '/api/cron/news',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronNewsRoute = ApiPublicCronNewsRouteImport.update({
  id: '/api/public/cron/news',
  path: '/api/public/cron/news',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/noticias': typeof NoticiasRoute
  '/programacao': typeof ProgramacaoRoute
  '/promocoes': typeof PromocoesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/api/cron/news': typeof ApiCronNewsRoute
  '/api/public/debug-env': typeof ApiPublicDebugEnvRoute
  '/api/public/cron/news': typeof ApiPublicCronNewsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/noticias': typeof NoticiasRoute
  '/programacao': typeof ProgramacaoRoute
  '/promocoes': typeof PromocoesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin': typeof AdminIndexRoute
  '/api/cron/news': typeof ApiCronNewsRoute
  '/api/public/debug-env': typeof ApiPublicDebugEnvRoute
  '/api/public/cron/news': typeof ApiPublicCronNewsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/noticias': typeof NoticiasRoute
  '/programacao': typeof ProgramacaoRoute
  '/promocoes': typeof PromocoesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/api/cron/news': typeof ApiCronNewsRoute
  '/api/public/debug-env': typeof ApiPublicDebugEnvRoute
  '/api/public/cron/news': typeof ApiPublicCronNewsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contato'
    | '/noticias'
    | '/programacao'
    | '/promocoes'
    | '/admin/login'
    | '/admin/'
    | '/api/cron/news'
    | '/api/public/debug-env'
    | '/api/public/cron/news'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/noticias'
    | '/programacao'
    | '/promocoes'
    | '/admin/login'
    | '/admin'
    | '/api/cron/news'
    | '/api/public/debug-env'
    | '/api/public/cron/news'
  id:
    | '__root__'
    | '/'
    | '/contato'
    | '/noticias'
    | '/programacao'
    | '/promocoes'
    | '/admin/login'
    | '/admin/'
    | '/api/cron/news'
    | '/api/public/debug-env'
    | '/api/public/cron/news'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContatoRoute: typeof ContatoRoute
  NoticiasRoute: typeof NoticiasRoute
  ProgramacaoRoute: typeof ProgramacaoRoute
  PromocoesRoute: typeof PromocoesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ApiCronNewsRoute: typeof ApiCronNewsRoute
  ApiPublicDebugEnvRoute: typeof ApiPublicDebugEnvRoute
  ApiPublicCronNewsRoute: typeof ApiPublicCronNewsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/promocoes': {
      id: '/promocoes'
      path: '/promocoes'
      fullPath: '/promocoes'
      preLoaderRoute: typeof PromocoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programacao': {
      id: '/programacao'
      path: '/programacao'
      fullPath: '/programacao'
      preLoaderRoute: typeof ProgramacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias': {
      id: '/noticias'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof NoticiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/debug-env': {
      id: '/api/public/debug-env'
      path: '/api/public/debug-env'
      fullPath: '/api/public/debug-env'
      preLoaderRoute: typeof ApiPublicDebugEnvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/news': {
      id: '/api/cron/news'
      path: '/api/cron/news'
      fullPath: '/api/cron/news'
      preLoaderRoute: typeof ApiCronNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/news': {
      id: '/api/public/cron/news'
      path: '/api/public/cron/news'
      fullPath: '/api/public/cron/news'
      preLoaderRoute: typeof ApiPublicCronNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContatoRoute: ContatoRoute,
  NoticiasRoute: NoticiasRoute,
  ProgramacaoRoute: ProgramacaoRoute,
  PromocoesRoute: PromocoesRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
  ApiCronNewsRoute: ApiCronNewsRoute,
  ApiPublicDebugEnvRoute: ApiPublicDebugEnvRoute,
  ApiPublicCronNewsRoute: ApiPublicCronNewsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
